# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "data-table-app"
client_id = "f4e07991227d88695252c714c12bd062"
application_url = "https://page-quizzes-possible-ok.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://page-quizzes-possible-ok.trycloudflare.com/auth/callback",
  "https://page-quizzes-possible-ok.trycloudflare.com/auth/shopify/callback",
  "https://page-quizzes-possible-ok.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-01"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "vertical-app.myshopify.com"
